# Generated by Django 4.0 on 2022-03-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comment_author',
        ),
    ]
